//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DIVELOG.RC
//
#define IDR_MAINFRAME                   2
#define IDR_LOGTYPE                     3
#define IDS_OLDVER                      4
#define IDS_TABLES                      5
#define NEXTPAGEU                       6
#define IDD_ABOUTBOX                    100
#define IDC_NEXTPAGE                    102
#define IDC_MFC_VER                     102
#define IDC_PREVPAGE                    103
#define IDD_DIALOG_BAR                  103
#define IDD_FRONT_PAGE                  104
#define IDD_DIVE_PAGE1                  105
#define DVL_DATECHANGED                 105
#define IDC_RELEASED                    105
#define IDD_DIVE_PAGE2                  106
#define IDB_TANKS                       106
#define IDB_DIVEPG1                     106
#define ID_BINTIMER                     106
#define IDC_DEBUG                       106
#define IDD_BACK_PAGE                   107
#define IDC_TAB_CONTROL                 107
#define IDD_PROP                        108
#define IDB_FRONT_PG_OLD                111
#define IDB_PICTURE                     112
#define IDB_DIVEPG2                     112
#define IDB_FRONT_PG                    113
#define IDI_BIN                         115
#define IDR_REPORTTYPE                  116
#define IDD_GENERAL                     117
#define IDB_BIN                         118
#define IDC_DIVEREC                     119
#define IDR_REPORT                      119
#define IDD_LOCATIONS                   122
#define IDD_DEFAULTS                    123
#define IDD_REPORTS_MAIN                125
#define IDD_REPORT_FILTER               127
#define IDD_REPORT_ORDER                128
#define IDD_DIVE_PAGE4                  129
#define IDD_REPORT_HEADER               130
#define IDD_REPORT_COLOPT               131
#define IDC_NODROP                      132
#define IDD_WIN95_DIVE_PAGE1            132
#define IDD_WIN95_FRONT_PAGE            133
#define IDD_WIN95_BACK_PAGE             134
#define IDD_WIN95_DIVE_PAGE2            135
#define IDD_NOTES                       136
#define IDD_REPORTS                     137
#define IDB_SPLASH                      138
#define IDD_SPLASH                      139
#define IDD_REGISTER                    140
#define IDD_THOUGHT_DAY                 141
#define IDD_DIALOG_BAR_TEMP             142
#define IDD_REPORTS_FILTER              143
#define IDD_BUDDY_PAGE1                 144
#define IDD_DIVE_PAGE5                  144
#define IDD_BUDDY_PAGE2                 145
#define IDD_WIN95_BUDDY_PAGE1           146
#define IDD_WIN95_BUDDY_PAGE2           147
#define IDD_FRONT_PAGE_800              148
#define IDD_BACK_PAGE_800               149
#define IDD_BUDDY_PAGE1_800             150
#define IDD_BUDDY_PAGE2_800             151
#define IDD_DIVE_PAGE1_800              152
#define IDD_DIVE_PAGE2_800              153
#define IDB_SCROLL                      200
#define IDB_SCROLL_LEFT                 201
#define IDB_SCROLL_RIGHT                202
#define IDB_SCROLL_LEFT_DIS             203
#define IDB_SCROLL_RIGHT_DIS            204
#define IDC_AVAIL_MEM                   500
#define IDC_MATH_COPR                   501
#define IDC_MATH_COPR_TXT               501
#define IDC_DISK_SPACE                  502
#define IDC_DUMMY_BUTTON                1002
#define IDC_BUTTON1                     1008
#define IDS_DISK_SPACE_UNAVAIL          1008
#define IDS_DISK_SPACE                  1009
#define IDC_BUTTON_B                    1009
#define IDC_LOCATION_COMBO              1010
#define IDS_MATH_COPR_NOTPRESENT        1010
#define IDC_BUTTON_C                    1010
#define IDS_MATH_COPR_PRESENT           1011
#define IDC_BUTTON_D                    1011
#define IDS_AVAIL_MEM                   1012
#define IDC_BUTTON_E                    1012
#define IDS_PHYSICAL_MEM                1013
#define IDC_BUTTON_F                    1013
#define IDC_RADIO_AIR                   1014
#define IDC_BUTTON_G                    1014
#define IDC_RADIO_AIR_WARM              1015
#define IDC_BUTTON_H                    1015
#define IDC_RADIO_AIR_HOT               1016
#define IDC_BUTTON_I                    1016
#define IDC_EDIT1                       1017
#define IDC_NAME                        1017
#define IDC_VALUE1                      1017
#define IDC_REPNAME                     1017
#define IDC_BUTTON_M                    1017
#define IDC_EDIT2                       1018
#define IDC_COMPANY                     1018
#define IDC_VALUE2                      1018
#define IDC_REPWIDTH                    1018
#define IDC_BUTTON_L                    1018
#define IDC_RADIO_VIS                   1019
#define IDC_VALUE3                      1019
#define IDC_BUTTON_K                    1019
#define IDC_VIS_MEDIUM                  1020
#define IDC_BUTTON_J                    1020
#define IDC_VIS_POOR                    1021
#define IDC_BUTTON_N                    1021
#define IDC_EDIT_STOP                   1022
#define IDC_BUTTON_O                    1022
#define IDC_RADIO_SURFACE               1023
#define IDC_BUTTON_P                    1023
#define IDC_EDIT_BOTTOM_TIME            1024
#define IDC_BUTTON_Q                    1024
#define IDC_EDIT_TIME_OUT               1025
#define IDC_CHECK_FRESH                 1025
#define IDC_BUTTON_R                    1025
#define IDC_CHECK_SALT                  1026
#define IDC_RADIO_SURFACE_WARM          1026
#define IDC_BUTTON_S                    1026
#define IDC_CHECK_SHORE                 1027
#define IDC_RADIO_SURFACE_HOT           1027
#define IDC_BUTTON_T                    1027
#define IDC_RADIO_BOTTOM                1028
#define IDC_CHECK_BOAT                  1028
#define IDC_BUTTON_U                    1028
#define IDC_CHECK_WAVES                 1029
#define IDC_RADIO_BOTTOM_WARM           1029
#define IDC_BUTTON_V                    1029
#define IDC_CHECK_CURRENT               1030
#define IDC_RADIO_BOTTOM_HOT            1030
#define IDC_BUTTON_Z                    1030
#define IDC_CHECK_SURF                  1031
#define IDC_BUTTON_Y                    1031
#define IDC_CHECK_SURGE                 1032
#define IDC_BUTTON_X                    1032
#define IDC_CHECK_DRYSUIT               1033
#define IDC_BUTTON_W                    1033
#define IDC_CHECK_WETSUIT               1034
#define IDC_CHECK_SEMI_DRYSUIT          1035
#define IDC_CHECK_UNDERSUIT             1036
#define IDC_CHECK_GLOVES                1037
#define IDC_CHECK_MITTENS               1038
#define IDC_CHECK_HOOD                  1039
#define IDC_CHECK_SOCKS                 1040
#define IDC_EDIT_WEIGHT                 1041
#define IDC_EDIT_DATE                   1042
#define IDC_EDIT_VIS                    1043
#define IDC_MEASURE_VIS                 1044
#define IDC_EDIT_AIR_START              1045
#define IDC_MEASURE_AIR_START           1046
#define IDC_EDIT_AIR_END                1047
#define IDC_MEASURE_AIR_END             1048
#define IDC_EDIT_TIME_IN                1049
#define IDC_EDIT_SI                     1050
#define IDC_EDIT_DEPTH                  1051
#define IDC_MEASURE_WEIGHT              1052
#define IDC_MEASURE_DEPTH               1053
#define IDC_NOTES                       1054
#define IDC_PG_BEFORE                   1055
#define IDC_PG_AFTER                    1056
#define IDC_EDIT_FRONT                  1057
#define IDC_TEST                        1060
#define IDC_LOCATIONS                   1062
#define IDC_ADD                         1063
#define IDC_REMOVE                      1064
#define IDC_LOCATION_LIST               1065
#define IDC_TANK_BAR                    1066
#define IDC_TANK_PSI                    1067
#define IDC_WEIGHT_LBS                  1068
#define IDC_WEIGHT_KGS                  1069
#define IDC_DEPTH_MTS                   1070
#define IDC_DEPTH_FT                    1071
#define IDC_NONE                        1072
#define IDC_NODEFAULT                   1072
#define IDC_COLUMNS                     1073
#define IDC_REP_COLS                    1074
#define IDC_DISPLAY_COMBO               1075
#define IDC_LESS                        1076
#define IDC_LESS_EQUAL                  1077
#define IDC_OPEN_BRACK                  1078
#define IDC_MORE                        1079
#define IDC_DELETE                      1084
#define IDC_SUBTRACT                    1085
#define IDC_INC_DATE                    1085
#define IDC_MULTIPLY                    1086
#define IDC_DIVIDE                      1087
#define IDC_INC_PAGENO                  1089
#define IDC_COLUMNS_LIST                1090
#define IDC_REPCOLS_LIST                1091
#define IDC_REMOVE_ALL                  1092
#define IDC_INSERT_ALL                  1093
#define IDC_INSERT                      1094
#define IDC_MOVE_UP                     1095
#define IDC_MOVE_DOWN                   1096
#define IDC_OPTIONS                     1097
#define IDC_FILTER                      1098
#define IDC_ORDER                       1099
#define IDC_HEADER                      1100
#define IDC_DEST_COMBO                  1101
#define IDC_LOAD                        1102
#define IDC_SAVE                        1103
#define IDC_REC_COUNT                   1104
#define IDC_CLEAR                       1105
#define IDC_EQUAL                       1106
#define IDC_CLOSE_BRACK                 1107
#define IDC_MORE_EQUAL                  1108
#define IDC_NOT_EQUAL                   1109
#define IDC_AND                         1110
#define IDC_OR                          1111
#define IDC_NOT                         1112
#define IDC_LIKE                        1113
#define IDC_VALUE                       1114
#define IDC_FORMULA                     1115
#define IDC_HEADER_TEXT                 1116
#define IDC_COL_HEADER                  1117
#define IDC_COL_WIDTH                   1118
#define IDC_ABT_TO_DATE                 1119
#define IDC_ABT_ALL_DIVES               1120
#define IDC_MATH_TXT                    1120
#define IDC_GRP_WEIGHT                  1121
#define IDC_GRP_DIVE                    1122
#define IDC_GRP_EXP                     1123
#define IDC_RNT                         1127
#define IDC_ABT                         1128
#define IDC_TBT                         1129
#define IDC_COLS_LIST                   1130
#define IDC_LOC_COMBO                   1131
#define IDC_AUTHOR                      1132
#define IDC_THOUGHT                     1133
#define IDC_SHOW                        1134
#define IDC_COLUMN1                     1135
#define IDC_OPER1                       1136
#define IDC_JOIN1                       1137
#define IDC_COLUMN2                     1138
#define IDC_BUTTON_A                    1138
#define IDC_OPER2                       1139
#define IDC_JOIN2                       1140
#define IDC_COLUMN3                     1141
#define IDC_OPER3                       1142
#define IDC_TITLE                       1142
#define IDC_FIRSTNAME                   1143
#define IDC_LASTNAME                    1144
#define IDC_ADDRESS                     1145
#define IDC_PHONE                       1146
#define IDC_FAX                         1147
#define IDM_DIVE_NEW                    32773
#define IDM_DIVE_REMOVE                 32774
#define IDM_RECORD_FIRST                32775
#define IDM_RECORD_PREV                 32776
#define IDM_RECORD_NEXT                 32777
#define IDM_RECORD_LAST                 32778
#define IDM_OPTIONS                     32779
#define IDM_EDIT_LOCATIONS              32780
#define IDM_DEF_SETTTINGS               32781
#define IDM_REPORTS                     32782
#define ID_FILE_PRINT_BLANK             32783
#define ID_REPORT_OPEN                  32784
#define ID_REPORT_SAVE                  32785
#define IDM_TEST                        32787
#define IDC_MATH                        65535
#define ID_STATIC                       65535
#define ID_STATIC2                      65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1148
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
