// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//

#define OEMRESOURCE

#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions (including VB)
//#include <afxole.h> 

// define the TBX frame symbols here for MFC 2.5 (or in the compiler options dialog)
#define TBX_MDIFRAME      // this is an MDI application
//#define TBX_OLEIPFRAME    // this application suuports OLE in-place activation

// include the TOOLARX.H file here
#include "toolbarx.h"