//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DIVELOG.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDC_COMMENTS                    101
#define IDC_AVAIL_MEM                   101
#define ID_COMMENTS_ZOOM                102
#define ID_VISBUT_GOOD                  103
#define IDD_SPLASH                      103
#define IDB_COMBO3                      104
#define IDB_COMBO                       104
#define ID_VISBUT_OK                    104
#define IDD_REGISTER                    104
#define IDD_TOOLBAR_PROP                105
#define ID_VISBUT_POOR                  105
#define IDB_TANKS                       106
#define ID_CHECK_FRESH                  106
#define IDC_MATH_COPR                   106
#define IDR_REPORTFRAME                 106
#define ID_CHECK_SALT                   107
#define IDC_DISK_SPACE                  107
#define ID_CHECK_SHORE                  108
#define IDD_TOOLTIP                     108
#define ID_CHECK_BOAT                   109
#define IDB_CHECKDOWN                   109
#define ID_CHECK_WAVES                  110
#define IDD_THOUGHT_DAY                 110
#define ID_CHECK_CURRENT                111
#define IDB_PICTURE                     112
#define ID_CHECK_SURF                   112
#define ID_CHECK_SURGE                  113
#define IDD_COMMENTS                    114
#define ID_CHECK_SOCKS                  114
#define ID_CHECK_HOOD                   115
#define ID_CHECK_MITTENS                116
#define IDD_LOCATIONLIST                117
#define ID_CHECK_GLOVES                 117
#define ID_CHECK_USUIT                  118
#define IDD_DIALOG                      118
#define ID_CHECK_DSUIT                  119
#define ID_CHECK_SEMIDSUIT              120
#define ID_CHECK_WETSUIT                121
#define ID_CHECK_COSTUME                122
#define ID_TEMP_AIR_LOW                 123
#define ID_TEMP_AIR_MED                 124
#define ID_TEMP_AIR_HIGH                125
#define ID_TEMP_SURFACE_LOW             126
#define ID_TEMP_SURFACE_MED             127
#define ID_TEMP_SURFACE_HIGH            128
#define ID_TEMP_BOTTOM_LOW              129
#define ID_TEMP_BOTTOM_MED              130
#define ID_TEMP_BOTTOM_HIGH             131
#define ID_CUR_FIELD                    132
#define ID_CHECKBOX                     133
#define ID_SPLASH                       134
#define IDDC_COMMENTS                   1000
#define IDC_RELEASED                    1000
#define IDC_SHOW                        1000
#define IDC_DEBUG                       1001
#define IDC_TOOLTIPS                    1002
#define IDC_FONT                        1003
#define IDC_LIST                        1004
#define IDC_NAME                        1004
#define IDC_TIME                        1004
#define IDC_DELETE                      1005
#define IDC_SETTEXTCOLOR                1005
#define IDC_ADD                         1006
#define IDC_COMPANY                     1006
#define IDC_SETFILLCOLOR                1006
#define IDC_SAMPLE_TEXT                 1007
#define IDS_DISK_SPACE_UNAVAIL          1008
#define IDC_SAMPLE_FILL                 1008
#define IDS_DISK_SPACE                  1009
#define IDS_MATH_COPR_NOTPRESENT        1010
#define IDS_MATH_COPR_PRESENT           1011
#define IDC_THOUGHT                     1011
#define IDS_AVAIL_MEM                   1012
#define IDC_AUTHOR                      1013
#define IDM_LOCATIONS                   10000
#define ID_RECORD_ADD                   10001
#define ID_RECORD_DELETE                10002
#define ID_REPORTS                      10003
#define IDM_RECORD_NEXT                 10005
#define IDM_RECORD_PREV                 10006
#define IDM_RECORD_FIRST                10007
#define IDM_RECORD_LAST                 10008
#define ID_TOOLBAR_PROP                 32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         10009
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           134
#endif
#endif
